### ISSUE TITLE
Set Up Cross-compilation Environment

### ISSUE THREAD

**Issue by grayfox-dev** [carrera1/pico_timer#1]
Others wanting to duplicate this code will need the toolchain. Toolchain set up can be tedious and easy to get wrong sometimes. Wouldn't it be great if we could just provide a Dockerfile for an environment to do the compilation? Yes it would.

Refer to the official [Pico-SDK Quickstart](https://github.com/raspberrypi/pico-sdk#quick-start-your-own-project)

**Comment by carrera1** [comment]
[bidirectional example here](https://github.com/raspberrypi/pico-examples/blob/master/multicore/multicore_runner/multicore_runner.c)

Would only need to send message to 2nd core through FIFO, and forget about it. Send it a pointer to some arbitrary routine that toggles an LED.

Fun idea would be to use a logic analyzer to compare when the time delta between when the separate LED toggling routines begin, as we're running with the idea that one core will toggle an LED every 3 seconds and the second core will blink an LED 5x every three seconds.
